# Generated by Django 4.0.4 on 2022-04-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_post_content_remove_post_photo_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="photo",
            new_name="photos",
        ),
    ]
