# Generated by Django 4.0.4 on 2022-04-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_image_options_alter_image_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="photos",
        ),
        migrations.AddField(
            model_name="image",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="main.post",
            ),
        ),
    ]
