# Generated by Django 4.0.4 on 2022-04-20 21:03

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_post_liked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Фотографии",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.ImageField(
                upload_to=main.helpers.helpers.PathAndRenameDate(
                    "photos/posts/%Y/%m/%d/"
                ),
                verbose_name="Фото",
            ),
        ),
    ]
