# Generated by Django 4.0.4 on 2022-04-23 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0011_remove_image_post_post_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked",
                related_query_name="liked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайкнувшие",
            ),
        ),
    ]
