# Generated by Django 4.0.4 on 2022-04-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_image_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('created_at',), 'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
