# Generated by Django 4.0.4 on 2022-05-08 09:26

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_image_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.helpers.PathAndRename('photos/posts/2022/5/8/'), verbose_name='Фото'),
        ),
    ]
