# Generated by Django 4.0.4 on 2022-05-22 09:44

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_comment_options_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.helpers.PathAndRename('photos/posts/2022/5/22/'), verbose_name='Фото'),
        ),
    ]
