# Generated by Django 4.0.4 on 2022-06-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
