# Generated by Django 4.0.4 on 2022-07-17 11:21

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_image_photo_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.helpers.PathAndRename('photos/posts/2022/7/17/'), verbose_name='Фото'),
        ),
    ]
