# Generated by Django 4.0.4 on 2022-07-18 08:13

from django.db import migrations, models
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.PathAndRename('photos/posts/2022/7/18/'), verbose_name='Фото'),
        ),
    ]
