# Generated by Django 4.0.4 on 2022-08-14 13:48

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_image_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.ImageField(
                upload_to=main.helpers.helpers.PathAndRenameDate(
                    "photos/posts/2022/8/14/"
                ),
                verbose_name="Фото",
            ),
        ),
    ]
