# Generated by Django 4.0.4 on 2022-08-19 17:39

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.helpers.PathAndRename('photos/posts/2022/8/19/'), verbose_name='Фото'),
        ),
    ]
