# Generated by Django 4.0.4 on 2022-09-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
    ]
