# Generated by Django 4.0.4 on 2022-09-11 15:48

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.helpers.PathAndRename('photos/posts/%Y/%m/'), verbose_name='Фото'),
        ),
    ]
