# Generated by Django 4.0.4 on 2022-09-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_alter_image_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ("created_at",),
                "verbose_name": "фото",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
