# Generated by Django 4.0.4 on 2022-10-04 20:40

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=main.helpers.helpers.PathAndRename('photos/posts/2022/10/'), verbose_name='Фото'),
        ),
    ]
