# Generated by Django 4.0.4 on 2022-11-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_alter_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_active",
        ),
    ]
