# Generated by Django 4.0.4 on 2022-05-15 10:27

from django.db import migrations, models
import main.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_contact_user_from_alter_contact_user_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.png', upload_to=main.helpers.PathAndRename('photos/2022/5/15/'), verbose_name='Аватарка'),
        ),
    ]
