# Generated by Django 4.0.4 on 2022-07-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_alter_profile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_verify",
        ),
        migrations.DeleteModel(
            name="Token",
        ),
    ]
