# Generated by Django 4.0.4 on 2022-08-07 09:40

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default/default.png",
                upload_to=main.helpers.helpers.PathAndRenameDate("photos/2022/8/7/"),
                verbose_name="Аватарка",
            ),
        ),
    ]
