# Generated by Django 4.0.4 on 2022-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='following', through='authentication.Contact', to='authentication.profile'),
        ),
    ]
