# Generated by Django 4.0.4 on 2022-08-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_profile_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="user_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_set",
                to="authentication.profile",
                verbose_name="От",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_set",
                to="authentication.profile",
                verbose_name="На",
            ),
        ),
    ]
