# Generated by Django 4.0.4 on 2022-08-11 09:30

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_contact_user_from_alter_contact_user_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.png', upload_to=main.helpers.helpers.PathAndRename('photos/2022/8/11/'), verbose_name='Аватарка'),
        ),
    ]
