# Generated by Django 4.0.4 on 2022-08-11 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0034_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                default=datetime.datetime(2022, 8, 11, 18, 18, 4, 585775, tzinfo=utc),
                verbose_name="День рождения",
            ),
            preserve_default=False,
        ),
    ]
