# Generated by Django 4.0.4 on 2022-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0035_profile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="День рождения"),
        ),
    ]
