# Generated by Django 4.0.4 on 2022-08-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0038_country_region_subregion_city"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="region",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="region",
            name="country",
        ),
        migrations.RemoveField(
            model_name="subregion",
            name="country",
        ),
        migrations.RemoveField(
            model_name="subregion",
            name="region",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.DeleteModel(
            name="SubRegion",
        ),
    ]
