# Generated by Django 4.0.4 on 2022-08-14 13:48

from django.db import migrations, models
import django.db.models.deletion
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('authentication', '0039_alter_region_unique_together_remove_region_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.png', upload_to=main.helpers.helpers.PathAndRename('photos/2022/8/14/'), verbose_name='Аватарка'),
        ),
    ]
