# Generated by Django 4.0.4 on 2022-10-04 20:40

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0051_alter_profile_birthday_alter_profile_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default/default.png",
                upload_to=main.helpers.helpers.PathAndRenameDate("photos/avatars/"),
                verbose_name="Аватарка",
            ),
        ),
    ]
