# Generated by Django 4.0.4 on 2022-11-14 09:47

from django.db import migrations, models
import main.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0052_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=main.helpers.helpers.PathAndRenameDate("photos/avatars/"),
                verbose_name="Аватарка",
            ),
        ),
    ]
